version: "3"

services:
  metadata:
    container_name: metadata
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    env_file:
      - .env
    ports:
      - 1000:1000
    volumes:
      - ./:/app/